In [91]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
from scipy.stats import zscore
import seaborn as sns
%matplotlib inline

In [92]:
df = pd.read_csv("Inc_Exp_Data.csv")

In [93]:
df.shape

(50, 7)

In [94]:
df.head()

,Mthly_HH_Income,Mthly_HH_Expense,No_of_Fly_Members,Emi_or_Rent_Amt,Annual_HH_Income,Highest_Qualified_Member,No_of_Earning_Members
0,5000,8000,3,2000,64200,Under-Graduate,1
1,6000,7000,2,3000,79920,Illiterate,1
2,10000,4500,2,0,112800,Under-Graduate,1
3,10000,2000,1,0,97200,Illiterate,1
4,12500,12000,2,3000,147000,Graduate,1

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Mthly_HH_Income           50 non-null     int64
 1   Mthly_HH_Expense          50 non-null     int64
 2   No_of_Fly_Members         50 non-null     int64
 3   Emi_or_Rent_Amt           50 non-null     int64
 4   Annual_HH_Income          50 non-null     int64
 5   Highest_Qualified_Member  50 non-null     object
 6   No_of_Earning_Members     50 non-null     int64
dtypes: int64(6), object(1)
memory usage: 2.9+ KB

In [96]:
df.isnull().sum()

Mthly_HH_Income             0
Mthly_HH_Expense            0
No_of_Fly_Members           0
Emi_or_Rent_Amt             0
Annual_HH_Income            0
Highest_Qualified_Member    0
No_of_Earning_Members       0
dtype: int64

In [97]:
df.describe()

,Mthly_HH_Income,Mthly_HH_Expense,No_of_Fly_Members,Emi_or_Rent_Amt,Annual_HH_Income,No_of_Earning_Members
count,50.000000,50.000000,50.000000,50.000000,5.000000e+01,50.000000
mean,41558.000000,18818.000000,4.060000,3060.000000,4.900190e+05,1.460000
std,26097.908979,12090.216824,1.517382,6241.434948,3.201358e+05,0.734291
min,5000.000000,2000.000000,1.000000,0.000000,6.420000e+04,1.000000
25%,23550.000000,10000.000000,3.000000,0.000000,2.587500e+05,1.000000
50%,35000.000000,15500.000000,4.000000,0.000000,4.474200e+05,1.000000
75%,50375.000000,25000.000000,5.000000,3500.000000,5.947200e+05,2.000000
max,100000.000000,50000.000000,7.000000,35000.000000,1.404000e+06,4.000000

In [98]:
df.describe(include='all')

,Mthly_HH_Income,Mthly_HH_Expense,No_of_Fly_Members,Emi_or_Rent_Amt,Annual_HH_Income,Highest_Qualified_Member,No_of_Earning_Members
count,50.000000,50.000000,50.000000,50.000000,5.000000e+01,50,50.000000
unique,NaN,NaN,NaN,NaN,NaN,5,NaN
top,NaN,NaN,NaN,NaN,NaN,Graduate,NaN
freq,NaN,NaN,NaN,NaN,NaN,19,NaN
mean,41558.000000,18818.000000,4.060000,3060.000000,4.900190e+05,NaN,1.460000
std,26097.908979,12090.216824,1.517382,6241.434948,3.201358e+05,NaN,0.734291
min,5000.000000,2000.000000,1.000000,0.000000,6.420000e+04,NaN,1.000000
25%,23550.000000,10000.000000,3.000000,0.000000,2.587500e+05,NaN,1.000000
50%,35000.000000,15500.000000,4.000000,0.000000,4.474200e+05,NaN,1.000000
75%,50375.000000,25000.000000,5.000000,3500.000000,5.947200e+05,NaN,2.000000
max,100000.000000,50000.000000,7.000000,35000.000000,1.404000e+06,NaN,4.000000

In [99]:
print(df['Mthly_HH_Income'].mean())
print(df['Mthly_HH_Income'].median())

41558.0
35000.0

In [100]:
print(df['Mthly_HH_Income'].mode())

0    45000
Name: Mthly_HH_Income, dtype: int64

In [101]:
mean=df['Mthly_HH_Expense'].mean()
print(mean)

18818.0

In [102]:
median=df['Mthly_HH_Expense'].median()
print(median)

15500.0

In [103]:
Max = df['Mthly_HH_Income'].max()
Min = df['Mthly_HH_Income'].min()
print(Max)
print(Min)

100000
5000

In [104]:
Range = Max - Min
print(Range)

95000

In [105]:
ratio = (df['Mthly_HH_Income'])/(df['Mthly_HH_Expense'])
print(ratio.max())

7.777777777777778

In [106]:
df['ratio'] = (df['Mthly_HH_Income'])/(df['Mthly_HH_Expense'])
houseidx = df['ratio'].idxmax()
print(houseidx)

42

In [107]:
print(df['No_of_Fly_Members'].mean())

4.06

In [108]:
print(df['No_of_Fly_Members'].std())

1.5173822786601394

In [109]:
non_earn=df['No_of_Fly_Members']-df['No_of_Earning_Members']
print(non_earn)

0     2
1     1
2     1
3     0
4     1
5     1
6     2
7     4
8     1
9     2
10    2
11    5
12    2
13    4
14    2
15    2
16    2
17    3
18    1
19    3
20    4
21    3
22    5
23    2
24    2
25    2
26    3
27    3
28    3
29    3
30    3
31    4
32    1
33    3
34    4
35    3
36    3
37    1
38    4
39    2
40    5
41    2
42    1
43    3
44    3
45    4
46    3
47    3
48    2
49    5
dtype: int64

In [110]:
deperatio = ((non_earn)/(df['No_of_Fly_Members']))
print(deperatio.max())

0.8333333333333334

In [111]:
df['deperatio']=((non_earn)/(df['No_of_Fly_Members']))
ind=df['deperatio'].idxmax()
print(ind)

11

In [112]:
df['emi']=((df['Emi_or_Rent_Amt'])/(df['Mthly_HH_Income']))*100
print(df['emi'].mean())

12.694386798751193

In [113]:
df['new_minc'] = df['Mthly_HH_Income']*0.4
houseind=df[df['Emi_or_Rent_Amt'] > df['new_minc']]

print(houseind.index.tolist())

[1, 6, 7, 11]

In [114]:
df['lowdis']=df['Mthly_HH_Income']-df['Mthly_HH_Expense']-df['Emi_or_Rent_Amt']

idx = df['lowdis'].idxmin()
print(idx)

6

In [115]:
df['expec_inc'] = df['Mthly_HH_Income']*12
dis = df['Annual_HH_Income'] - df['expec_inc']
print(dis)

0       4200
1       7920
2      -7200
3     -22800
4      -3000
5      28560
6     -12600
7          0
8      -9120
9     -19200
10     38400
11     15840
12     11232
13     28800
14    -43200
15    -54000
16    -39000
17    -42000
18         0
19     25200
20    -14640
21     61440
22    -77520
23     61200
24     46200
25     29400
26     88920
27    -67200
28    -15120
29    103200
30    -16200
31    -32400
32   -102600
33     70200
34     44160
35   -107160
36    -30000
37    -24240
38    -59400
39   -129600
40   -129600
41   -132600
42    -84000
43    115200
44    122400
45   -194400
46    -23520
47    204000
48   -168000
49    120000
dtype: int64

In [116]:
group = df.groupby('Highest_Qualified_Member')
avg_inc_by_qual_mean = group['Mthly_HH_Income'].mean()

avg_inc_by_qual_median = group['Mthly_HH_Income'].median()

avg_income_by_qual = pd.DataFrame({
    'mean': avg_inc_by_qual_mean,
    'median': avg_inc_by_qual_median
})

print(avg_income_by_qual)

                                  mean   median
Highest_Qualified_Member
Graduate                  40921.052632  35000.0
Illiterate                25280.000000  22000.0
Post-Graduate             59166.666667  52500.0
Professional              52550.000000  46000.0
Under-Graduate            29350.000000  22500.0

In [117]:
df['Zscore'] = stats.zscore(df['Mthly_HH_Income'])
outliers_inc = df[np.abs(df['Zscore']) > 3]
print(outliers_inc)
corr_inc_expense = df['Mthly_HH_Income'].corr(df['Mthly_HH_Expense'])
print(corr_inc_expense)
corr_earners_inc = df['No_of_Earning_Members'].corr(df['Mthly_HH_Income'])
print(corr_earners_inc)

Empty DataFrame
Columns: [Mthly_HH_Income, Mthly_HH_Expense, No_of_Fly_Members, Emi_or_Rent_Amt, Annual_HH_Income, Highest_Qualified_Member, No_of_Earning_Members, ratio, deperatio, emi, new_minc, lowdis, expec_inc, Zscore]
Index: []
0.6492152549316462
0.34788345602238385